# Generated by Django 4.2.1 on 2023-07-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solo_App', '0002_car_available_car_bookmarked_car_rent_days_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='bookmarked',
            field=models.ManyToManyField(related_name='bookmarked', to='Solo_App.user'),
        ),
    ]
